language: go
sudo: false
go:
  - 1.8
  - tip

before_install:
 - go get github.com/modocache/gover
 - go get github.com/mattn/goveralls
 
install:
- go get golang.org/x/tools/cmd/cover
 
script:
  - gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
