language: go
sudo: false
go:
  - 1.8
  - 1.10
  - tip

install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls
 
script:
  - go test -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
